# Generated by Django 6.0.3 on 2026-03-04 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_id', models.TextField()),
                ('receiver_id', models.TextField()),
                ('room', models.TextField()),
                ('message_text', models.TextField()),
                ('photo', models.ImageField(blank=True, null=True, upload_to='chat/photos/%Y/%m/%d/')),
                ('file', models.FileField(blank=True, null=True, upload_to='chat/files/%Y/%m/%d/')),
                ('voice_message', models.FileField(blank=True, null=True, upload_to='chat/voice/%Y/%m/%d/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='GroupData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.TextField(db_index=True)),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('created_by', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='groups/avatars/%Y/%m/%d/')),
            ],
            options={
                'db_table': 'group_data',
            },
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.TextField(db_index=True)),
                ('user_id', models.TextField(db_index=True)),
                ('role', models.TextField(default='member')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'group_members',
            },
        ),
        migrations.CreateModel(
            name='GroupMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_id', models.TextField()),
                ('group_id', models.TextField(db_index=True)),
                ('message_text', models.TextField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='groups/photos/%Y/%m/%d/')),
                ('file', models.FileField(blank=True, null=True, upload_to='groups/files/%Y/%m/%d/')),
                ('voice_message', models.FileField(blank=True, null=True, upload_to='groups/voice/%Y/%m/%d/')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'group_messages',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.TextField()),
                ('guest_id', models.TextField()),
                ('room', models.TextField()),
                ('count', models.TextField()),
                ('groups', models.TextField()),
            ],
        ),
    ]
