# Generated by Django 6.0.1 on 2026-02-08 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(max_length=225, unique=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('number', models.TextField()),
                ('status', models.TextField()),
                ('password', models.TextField()),
                ('token', models.TextField(unique=True)),
                ('sessuon_token_id_consuner', models.TextField(unique=True)),
            ],
        ),
    ]
