# Generated by Django 6.0.1 on 2026-05-15 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.TextField()),
                ('guests_id', models.TextField()),
                ('lobbi', models.TextField()),
                ('message', models.TextField()),
                ('read_message', models.TextField()),
            ],
        ),
    ]
